### ISSUE TITLE
Favorite button?

### ISSUE THREAD

**Issue by Papercog** [loucks1/Directolor-ESPHome#5]
Wondering how do I send the favorite position command? I'm using Home Assistant so I get controls in the GUI automatically for open, close, stop, tilt open and tilt close. 

(Chit chat)
I've used Wevolor since I got these blinds ~3 years ago, but my Wevolor stopped working so I finally wired up the NRF24L01+ and ESP32 that I purchased....shortly after setting up Wevolor. I'm happy with how responsive this is, being able to skip the relay race through the remote.

Don't think it matters, but mine are top-down bottom-up shades. For the curious - the top motor and bottom motor cannot be controlled independently but the tilt function operates the top-down motor, so long as the bottom of the shade is lowered fully. They use the same 6 channel remote as other Leveler blinds and shades of this era (including the same programming instructions). 

```
esp32:
  board: sparkfun_esp32s2_thing_plus_c
  framework:
    type: arduino

external_components:
  source: github://loucks1/Directolor-ESPHome

esphome:
  name: levolordirect
  friendly_name: LevolorDirect

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "secret"

ota:
  - platform: esphome
    password: "secret"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Levolordirect Fallback Hotspot"
    password: "secret"

captive_portal:

nrf24l01_base:
  id: nrf24l01
  ce_pin: 22
  cs_pin: 21

button:
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"

cover:
  - platform: directolor_cover
    base: nrf24l01
    id: my_directolor_cover
    name: My Directolor Cover
    radio_code:   #AA AA AA AA
      - 0xAA
      - 0xAA
      - 0xAA
      - 0xAA
    channel: 1
    movement_duration: 16s
    tilt_supported: true
    favorite_support: true
    program_support: true
  - platform: directolor_cover
    base: nrf24l01
    id: my_directolor_cover2
    name: My Directolor Cover2
    radio_code:   #AA AA AA AA
      - 0xAA
      - 0xAA
      - 0xAA
      - 0xAA
    channel: 2
    movement_duration: 16s
    tilt_supported: true
    favorite_support: true
    program_support: true
  ```

**Comment by Papercog** [comment]
I do get a ESP Reset button consistent with adding the Button platform. So I think adding additional buttons in the button section will cause those to be created in Home Assistant. What I'm less sure of is how to link that button back to the favorite command in this library. I know just enough to be ... annoying (thanks in advance).

**Comment by Papercog** [comment]
(Sorry, also stumbling through this part of the GitHub UX I'm less familiar with. I'll go break my own projects lol)

**Comment by loucks1** [comment]
Hey - sorry - I'm on vacation - I have a branch with Favorite in it, but I'm not positive how I implemented that - I'll get back to you ASAP on this once I return.

**Comment by loucks1** [comment]
This has taken a bit longer than planned - the gov shutdown has made extra work for me.  Anyway, can you please try this and see what it does for you:

```
packages:
  directolor:
    url:  https://github.com/loucks1/Directolor-ESPHome
    files:
      - path: directolor_cover.yaml
        vars:
          id: blind1
          name: Directolor Blind 1
          radio_code: 
            - 0x06
            - 0x03
            - 0x05
            - 0x12
          tilt_supported: true
          channel: 1
          disable_favorite_support: true
          disable_program_support: true
      - path: directolor_cover.yaml
        vars:
          id: blind2
          name: Directolor Blind 2
          radio_code: 
            - 0x06
            - 0x03
            - 0x05
            - 0x12
          tilt_supported: false
          channel: 2
          movement_duration: 17s
          disable_favorite_support: false
          disable_program_support: false
    ref: IssueWithFavoriteAndProgram 
    refresh: 2s
```

If this works for you, and I believe it will, then I'll commit to main and eventually you can remove the ref and refresh at the end.  

If you visit the esphome device, you should see all the buttons

for Blind 2, you should all the buttons in Home Assistant and for Blind 1, you should see that they are disabled (but you can still enable them).  

This replaces the rest of the config - so need to declare anything else - don't pull in the external packages, don't create the nrf24l01_base - it is handled by the package.  If you need to change the CE/CS pins, let me know and I'll tell you how to do it or you can just look at the package yaml for the proper vars.  

I won't merge these changes into main until you confirm that you can do everything needed.  Thanks for your patience on this.

**Comment by loucks1** [comment]
If you are using webserver 3, there are some nuances, you will want to set the values for the disable entities to false, so that they show in ESPHome.

**Comment by Papercog** [comment]
This got it working for how I want to use it. **Thank you!**

The web server still isn't working for me, but I think that might be a network issue on my end.

Here is my full config, if it's helpful to you. I wanted to keep the Home Assistant stuff in. I needed to remove the "cover:" section for it to pick up the version of covers you defined, and then it brought into Home Assistant the program and favorite buttons.

The way the top-down works with the tilt-slider is a little funky, but not of concern to me right now (and maybe something I can experiment with on my own in a different branch in the future)

I personally then disabled the programming support (in the config, as reflected below) and the "Set favorite" buttons (Just in Home Assistant UI) as a safety / to prevent accidental or unintentional programming...which also means I didn't test those. I can, if that would be helpful. 

<img width="331" height="678" alt="Image" src="https://github.com/user-attachments/assets/250ec3d6-5abe-4e6d-b015-66e6dc8e7751" />

```
esp32:
  board: sparkfun_esp32s2_thing_plus_c
  framework:
    type: arduino

packages:
  directolor:
    url:  https://github.com/loucks1/Directolor-ESPHome
    files:
      - path: directolor_cover.yaml
        vars:
          id: blind1
          name: Living Room Shade - Left
          radio_code: 
            - 0xC1
            - 0x8A
            - 0xC5
            - 0x60
          tilt_supported: true
          channel: 1
          movement_duration: 21s
          disable_favorite_support: false
          disable_program_support: true
      - path: directolor_cover.yaml
        vars:
          id: blind2
          name: Living Room Shade - Right
          radio_code: 
            - 0xC1
            - 0x8A
            - 0xC5
            - 0x60
          tilt_supported: true
          channel: 2
          movement_duration: 17s
          disable_favorite_support: false
          disable_program_support: true
    ref: IssueWithFavoriteAndProgram 
    refresh: 2s
    
    
esphome:
  name: levolordirect
  friendly_name: LevolorDirect


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "KEY"


ota:
  - platform: esphome
    password: "PASSWORD"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Levolordirect Fallback Hotspot"
    password: "FALLBACK"

captive_portal:

nrf24l01_base:
  id: nrf24l01
  ce_pin: 22
  cs_pin: 21


button:
  # Your existing reboot button
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"
```

**Comment by loucks1** [comment]
take out the 

```
nrf24l01_base:
  id: nrf24l01
  ce_pin: 22
  cs_pin: 21
```

That is handled in the package.  You can leave the favorite support in as you have to physically touch the blind to *set* the favorite.  

Also, you *shouldn't* need the button anymore.  (I didn't test, because I want to be able to reboot for other reasons)

Finally, for the webserver, you can add something like:

```
web_server:
 port: 80
 #version: 3
```

I will merge this sometime today and then delete this branch.  I'll update this issue when I do it and then close it out.

**Comment by loucks1** [comment]
Also, if you want to discuss the top down support, open another issue and we can figure that out.

**Comment by loucks1** [comment]
This is now merged into main - please remove your ref: line or change it to:

```
ref: main
```
